name = "SignalPlots"
uuid = "c121886f-841d-4855-8f3a-15f9a2397416"
authors = ["Matt Karikomi <mattkarikomi@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
